{% set name = "apache-airflow-providers-microsoft-winrm" %}
{% set version = "3.11.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_microsoft_winrm-{{ version }}.tar.gz
  sha256: edf6ee66ea079dc6d7784a0896ca4a27fc677349d18e8f2ec30278afdbd5b60f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - apache-airflow-providers-common-compat >=1.8.0
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - pywinrm >=0.5.0

test:
  imports:
    - airflow.providers.microsoft.winrm
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-microsoft-winrm for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/microsoft/winrm/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-microsoft-winrm/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
