{% set name = "apache-airflow-providers-microsoft-winrm" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b903531b855a7ec48a2d75c35f69a95ce2de9b1b38931f07629617d7bf5aebd3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.8.0
    - pywinrm >=0.4

test:
  imports:
    - airflow.providers.microsoft.winrm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-microsoft-winrm for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/microsoft/winrm/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-microsoft-winrm/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
